# Generated by Django 5.1.5 on 2025-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_workerprofile_availability_workerprofile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
