# Generated by Django 5.1.5 on 2025-03-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
