# Generated by Django 5.1.5 on 2025-03-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_is_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_worker',
        ),
    ]
