# Generated by Django 5.1.5 on 2025-03-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_hirerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_hire_requests', to='user.workerprofile'),
        ),
    ]
