# Generated by Django 5.1.5 on 2025-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_hirerequest_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
