# Generated by Django 5.1.5 on 2025-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
