# Generated by Django 5.1.5 on 2025-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userprofile_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='used_points',
            field=models.IntegerField(default=0),
        ),
    ]
