# Generated by Django 5.1.5 on 2025-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_hirerequest_used_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
