# Generated by Django 5.1.5 on 2025-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_workerprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=150),
        ),
    ]
