# Generated by Django 5.2 on 2025-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_workerprofile_rejection_message_workerprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='workerprofilepics'),
        ),
    ]
