# Generated by Django 5.2 on 2025-04-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_workerprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=150),
        ),
    ]
