# Generated by Django 5.2 on 2025-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_workerprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reward_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
