# Generated by Django 5.2 on 2025-04-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
